### ISSUE TITLE
Unable to run the application.

### ISSUE THREAD

**Issue by sravanithamatamqualbrain** [zroyer/juggle-and-drop#3]
Hi Team,

I followed the steps mentioned to run the application.

But when i am running the command i.e, "npm run build", i am getting some errors and unable to run the application. 

Please help me to fix this issue. Please see the below attached images for error reference.

Thank you
Sravani Thamatam

[
<img width="956" alt="Webpack" src="https://user-images.githubusercontent.com/61418209/79300433-4d32e800-7f04-11ea-950a-4213b4add98f.PNG">
<img width="942" alt="BabelError" src="https://user-images.githubusercontent.com/61418209/79300437-51f79c00-7f04-11ea-8259-b2f673ea18b6.PNG">

]

**Comment by zroyer** [comment]
hey @sravanithamatamqualbrain, thanks for your interest in this project!
I've updated some of the packages, please let me know if you are still experiencing this issue!

**Comment by zroyer** [comment]
hey @sravanithamatamqualbrain, thanks for your interest in this project!
I've updated some of the packages, please let me know if you are still experiencing this issue!
